### PR TITLE
change the design of login component

### PR DESCRIPTION
**Pull request by gayathrik23**

### CODE REVIEW

**Comment by Swadeshit27** [comment]
@gayathrik23 resolve the confilcts

**Comment by gayathrik23** [comment]
@Swadeshit27 resolved the conflicts.. can you check once

**Comment by gayathrik23** [comment]
@Swadeshit27 why one check was unsuccessful ... 
or shall i make another PR

**Comment by Swadeshit27** [comment]
@gayathrik23 first pull by writing git pull origin <branch name> then resolve the confilct. I see that your package.json file has conflicts.Don't create another pr

**Comment by gayathrik23** [comment]
> @gayathrik23 first pull by writing git pull origin then resolve the confilct. I see that your package.json file has conflicts.Don't create another pr

@Swadeshit27 after did this, it shows "everything is up to date" 
Screenshot (291)

**Comment by Swadeshit27** [comment]
if use npm command then delete yarn.lock folder and if you use yarn then delete package.json.

**Comment by gayathrik23** [comment]
@Swadeshit27 Your understanding means a lot; I hope that you won't be upset. It's my first time in open source... 
I will do again and raise PR

**Comment by Swadeshit27** [comment]
Ok for now You come to my repo and copy whole TopBar.jsx code and yarn.lock code and paste in your folder then conflict will resolve. I highly encourage you to learn basic about git.

**Comment by gayathrik23** [comment]
> Ok for now You come to my repo and copy whole TopBar.jsx code and yarn.lock code and paste in your folder then conflict will resolve. I highly encourage you to learn basic about git.

ok.. I will do that. Thank you  so much

**Comment by gayathrik23** [comment]
@Swadeshit27 can u check once

**Pull request merged**
