### PR TITLE
issue #3

### PR DESCRIPTION
**Pull request by SHABIN-K**

### CODE REVIEW

**Comment by Swadeshit27** [comment]
@SHABIN-K please wait there occured some issue after merge I resolve the issue then you pull first then resolve the confilicts.

**Comment by Swadeshit27** [comment]
@SHABIN-K  resolve the conflicts

**Comment by SHABIN-K** [comment]
> @SHABIN-K resolve the conflicts

resolved

**Comment by Swadeshit27** [comment]
@SHABIN-K  while scroll down the table the navbar also scroll down, fixed that issue

**Pull request closed without merging**
